# Generated by Django 3.2.9 on 2022-03-08 08:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('code', models.CharField(max_length=200)),
                ('certificate_number', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaxHubsSideAB',
            fields=[
                ('code', models.CharField(max_length=200)),
                ('m12', models.IntegerField(default=0)),
                ('m16', models.IntegerField(default=0)),
                ('m20', models.IntegerField(default=0)),
                ('m25', models.IntegerField(default=0)),
                ('m32', models.IntegerField(default=0)),
                ('m40', models.IntegerField(default=0)),
                ('m50', models.IntegerField(default=0)),
                ('m60', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaxHubsSideCD',
            fields=[
                ('code', models.CharField(max_length=200)),
                ('m12', models.IntegerField(default=0)),
                ('m16', models.IntegerField(default=0)),
                ('m20', models.IntegerField(default=0)),
                ('m25', models.IntegerField(default=0)),
                ('m32', models.IntegerField(default=0)),
                ('m40', models.IntegerField(default=0)),
                ('m50', models.IntegerField(default=0)),
                ('m60', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaximumPowerDissipation',
            fields=[
                ('code', models.CharField(max_length=200)),
                ('certificate_number', models.CharField(max_length=200)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('panels', models.JSONField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('conformity', models.BooleanField(blank=True, max_length=200, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Termina',
            fields=[
                ('code', models.CharField(max_length=200)),
                ('t15', models.IntegerField(default=0)),
                ('t25', models.IntegerField(default=0)),
                ('t40', models.IntegerField(default=0)),
                ('t60', models.IntegerField(default=0)),
                ('t100', models.IntegerField(default=0)),
                ('t160', models.IntegerField(default=0)),
                ('t350', models.IntegerField(default=0)),
                ('t500', models.IntegerField(default=0)),
                ('t700', models.IntegerField(default=0)),
                ('t950', models.IntegerField(default=0)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('name', models.CharField(default='', max_length=200)),
                ('code', models.CharField(blank=True, max_length=200, null=True)),
                ('overall_dimension_d', models.IntegerField(default=0)),
                ('overall_dimension_w', models.IntegerField(default=0)),
                ('overall_dimension_h', models.IntegerField(default=0)),
                ('internal_dimension_a', models.IntegerField(default=0)),
                ('internal_dimension_b', models.IntegerField(default=0)),
                ('internal_dimension_c', models.IntegerField(default=0)),
                ('mounting_plate_d', models.IntegerField(default=0)),
                ('mounting_plate_e', models.IntegerField(default=0)),
                ('fixing_dimension_f', models.IntegerField(default=0)),
                ('fixing_dimensions_g', models.IntegerField(default=0)),
                ('fixing_dimensions_screw', models.CharField(default='M 4/6', max_length=10)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('ambient_temperature', models.CharField(default='–40°C +60°C', max_length=200)),
                ('degree_of_protection', models.CharField(blank=True, default='IP66', max_length=200, null=True)),
                ('class_of_protection', models.CharField(blank=True, default='II', max_length=200, null=True)),
                ('temperature_class', models.CharField(blank=True, default='T6/T5/T4', max_length=200, null=True)),
                ('maximum_voltage', models.CharField(blank=True, default='1100 V', max_length=200, null=True)),
                ('maximum_current', models.CharField(blank=True, default='234 A', max_length=200, null=True)),
                ('mechanical_riskn', models.CharField(blank=True, default='7 J', max_length=200, null=True)),
                ('color', models.CharField(blank=True, default='Black', max_length=200, null=True)),
                ('type_of_protection', models.CharField(blank=True, default='Ex-e', max_length=200, null=True)),
                ('material', models.CharField(blank=True, default='Glass fiber reinforced polyester resin', max_length=200, null=True)),
                ('marking_gb_terminal_boxes', models.CharField(default='II 2GD Ex e ia IIC T6/T5 Gb', max_length=200)),
                ('marking_db_terminal_boxes', models.CharField(default='Ex tb IIIC T85/T100°C Db', max_length=200)),
                ('marking_gb_terminal_control_stations', models.CharField(default='II 2GD Ex d e [ia/ib] mb IIC T6/T5/T4 Gb', max_length=200)),
                ('marking_db_terminal_control_stations', models.CharField(default='Ex tb IIIC T85/T100/T135°C Db', max_length=200)),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('description_function', models.TextField(blank=True, null=True)),
                ('description_constructin', models.TextField(blank=True, null=True)),
                ('description_accessories', models.TextField(blank=True, null=True)),
                ('description_protection', models.TextField(blank=True, null=True)),
                ('conformity', models.CharField(blank=True, max_length=200, null=True)),
                ('protection_category', models.CharField(blank=True, default='suitable for Zone 1- 2 (gas) and Zone 21 - 22 (dust)', max_length=200, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('option', models.JSONField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box.certificate')),
                ('max_hubs_side_a_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box.maxhubssideab')),
                ('max_hubs_side_c_d', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box.maxhubssidecd')),
                ('maximum_power_dissipation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box.maximumpowerdissipation')),
                ('termina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box.termina')),
            ],
            options={
                'unique_together': {('max_hubs_side_a_b', 'max_hubs_side_c_d')},
            },
        ),
    ]
