# Generated by Django 3.2.9 on 2022-03-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='code',
            field=models.CharField(default='', max_length=200),
        ),
    ]
