# Generated by Django 3.2.9 on 2022-03-08 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('box', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('first_name', models.CharField(default='', max_length=200)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_adress', models.CharField(blank=True, max_length=200, null=True)),
                ('company_zip_code', models.CharField(blank=True, max_length=200, null=True)),
                ('company_city', models.CharField(blank=True, max_length=200, null=True)),
                ('company_country', models.CharField(blank=True, max_length=200, null=True)),
                ('person_name', models.CharField(blank=True, max_length=200, null=True)),
                ('person_adress', models.CharField(blank=True, max_length=200, null=True)),
                ('person_zip_code', models.CharField(blank=True, max_length=200, null=True)),
                ('person_city', models.CharField(blank=True, max_length=200, null=True)),
                ('person_country', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.IntegerField(default=0)),
                ('nip', models.IntegerField(default=0)),
                ('vat', models.IntegerField(default=0)),
                ('name_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_staf', models.BooleanField(default=False)),
                ('is_activ', models.BooleanField(default=False)),
                ('rodo', models.BooleanField(default=False)),
                ('status_text', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
                ('sys_note', models.TextField(blank=True, max_length=200, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('function', models.TextField(blank=True, null=True)),
                ('conformity', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('box', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='box.box')),
                ('component', models.ManyToManyField(to='order.Component')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('coments', models.CharField(default='', max_length=200)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('status_proc', models.BooleanField(default=False)),
                ('price', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=1)),
                ('last_name', models.CharField(default='', max_length=200)),
                ('position', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.IntegerField(default=0)),
                ('nip', models.IntegerField(default=0)),
                ('vat', models.IntegerField(default=0)),
                ('name_name', models.CharField(blank=True, max_length=200, null=True)),
                ('is_staf', models.BooleanField(default=False)),
                ('is_activ', models.BooleanField(default=False)),
                ('status_text', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=200, null=True)),
                ('sys_note', models.TextField(blank=True, max_length=200, null=True)),
                ('function', models.TextField(blank=True, null=True)),
                ('conformity', models.CharField(blank=True, max_length=200, null=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('product', models.ManyToManyField(to='order.Product')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.purchaser')),
            ],
        ),
        migrations.CreateModel(
            name='Gladns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('glands_type', models.CharField(default='', max_length=200)),
                ('glands_quan', models.CharField(default='', max_length=200)),
                ('glands_size', models.CharField(default='', max_length=200)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.brand')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='produkt_gladns_site_a',
            field=models.ManyToManyField(related_name='produkt_gladns_site_a_set', to='order.Gladns'),
        ),
        migrations.AddField(
            model_name='component',
            name='produkt_gladns_site_b',
            field=models.ManyToManyField(related_name='produkt_gladns_site_b_set', to='order.Gladns'),
        ),
        migrations.AddField(
            model_name='component',
            name='produkt_gladns_site_c',
            field=models.ManyToManyField(related_name='produkt_gladns_site_c_set', to='order.Gladns'),
        ),
        migrations.AddField(
            model_name='component',
            name='produkt_gladns_site_d',
            field=models.ManyToManyField(related_name='produkt_gladns_site_d_set', to='order.Gladns'),
        ),
    ]
