# Generated by Django 3.2.9 on 2022-03-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='product_gladns_site_a',
        ),
        migrations.RemoveField(
            model_name='component',
            name='product_gladns_site_b',
        ),
        migrations.RemoveField(
            model_name='component',
            name='product_gladns_site_c',
        ),
        migrations.RemoveField(
            model_name='component',
            name='product_gladns_site_d',
        ),
        migrations.AlterField(
            model_name='component',
            name='produkt_glands',
            field=models.ManyToManyField(blank=True, related_name='gland_set', to='order.Gladns'),
        ),
        migrations.AlterField(
            model_name='component',
            name='produkt_terminal',
            field=models.ManyToManyField(blank=True, related_name='terminal_set', to='order.Terminals'),
        ),
    ]
