# Generated by Django 3.2.9 on 2022-03-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220308_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='info_shotr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
