# Generated by Django 3.2.9 on 2022-03-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20220317_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='additional_options',
            field=models.ManyToManyField(blank=True, related_name='additional_set', to='order.Additional'),
        ),
    ]
