# Generated by Django 3.2.9 on 2022-03-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_info_shotr'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_inf',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='suppliers',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
