# Generated by Django 3.2.9 on 2022-03-08 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20220308_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='additional_options',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='additional_options2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='component',
            name='additional_options3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('glands_type', models.CharField(default='', max_length=200)),
                ('glands_quan', models.CharField(default='', max_length=200)),
                ('glands_size', models.CharField(default='', max_length=200)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.brand')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='produkt_terminal',
            field=models.ManyToManyField(related_name='terminal_set', to='order.Terminal'),
        ),
    ]
