# Generated by Django 3.2.9 on 2022-03-08 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20220308_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='additional_options',
        ),
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('options', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.brand')),
            ],
        ),
        migrations.AddField(
            model_name='component',
            name='additional_options',
            field=models.ManyToManyField(related_name='additional_set', to='order.Additional'),
        ),
    ]
