# Generated by Django 3.2.9 on 2022-03-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20220321_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaser',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='purchaser',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
