# Generated by Django 3.2.9 on 2022-03-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20220308_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='coments',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
