# Generated by Django 3.2.9 on 2022-03-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_coments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_inf',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
