# Generated by Django 3.2.9 on 2022-03-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20220323_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaser',
            name='smid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
