# Generated by Django 3.2.9 on 2022-03-31 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_purchaser_smid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='boxs_id',
            field=models.IntegerField(default=0),
        ),
    ]
