# Generated by Django 3.2.9 on 2022-03-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20220308_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gladns',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terminal',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
