# Generated by Django 3.2.9 on 2022-03-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20220308_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gladns',
            name='glands_quan',
        ),
        migrations.RemoveField(
            model_name='gladns',
            name='glands_size',
        ),
        migrations.RemoveField(
            model_name='gladns',
            name='glands_type',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='glands_quan',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='glands_size',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='glands_type',
        ),
        migrations.AddField(
            model_name='gladns',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terminal',
            name='af',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terminal',
            name='cable0mm1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='terminal',
            name='cable0mm12',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='terminal',
            name='cable0mm123',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='terminal',
            name='e',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terminal',
            name='l',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terminal',
            name='orderNr2070',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='terminal',
            name='orderNr5570',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='terminal',
            name='ou',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='terminal',
            name='size',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='terminal',
            name='type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='terminal',
            name='wieght',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Terminals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.brand')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.terminal')),
            ],
        ),
        migrations.CreateModel(
            name='Gladn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('type', models.CharField(default='', max_length=200)),
                ('size', models.CharField(default='', max_length=200)),
                ('cable0mm123', models.CharField(default='', max_length=200)),
                ('cable0mm12', models.CharField(default='', max_length=200)),
                ('cable0mm1', models.CharField(default='', max_length=200)),
                ('af', models.IntegerField(default=0)),
                ('l', models.IntegerField(default=0)),
                ('e', models.IntegerField(default=0)),
                ('wieght', models.IntegerField(default=0)),
                ('ou', models.IntegerField(default=0)),
                ('orderNr2070', models.CharField(default='', max_length=200)),
                ('orderNr5570', models.CharField(default='', max_length=200)),
                ('price', models.IntegerField(default=0)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.brand')),
            ],
        ),
        migrations.AddField(
            model_name='gladns',
            name='gladn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.gladn'),
        ),
        migrations.AlterField(
            model_name='component',
            name='produkt_terminal',
            field=models.ManyToManyField(related_name='terminals_set', to='order.Terminals'),
        ),
    ]
