# Generated by Django 3.2.9 on 2022-03-08 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20220308_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminal',
            old_name='cable0mm123',
            new_name='cable_0_mm_123',
        ),
    ]
