# Generated by Django 3.2.9 on 2022-03-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_rename_cable0mm123_terminal_cable_0_mm_123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='cable_0_mm_123',
        ),
        migrations.AddField(
            model_name='terminal',
            name='Width_length_height',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='color',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='current_voltage_UL_A_V',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='order_No',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='solid_AWG_stranded_AWG_mm2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='stranded_with_ferrule_AWG_mm2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='terminal',
            name='two_conduct_of_same_type_solid_str_mm2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gladn',
            name='cable0mm1',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gladn',
            name='cable0mm12',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gladn',
            name='cable0mm123',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
