# Generated by Django 3.2.9 on 2022-03-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20220308_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='gladn',
            name='color',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
