# Generated by Django 3.2.9 on 2022-03-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_auto_20220308_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='gladn',
            name='material',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='terminal',
            name='material',
            field=models.CharField(default='', max_length=200),
        ),
    ]
