# Generated by Django 3.2.9 on 2022-03-09 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_auto_20220308_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='gladns',
            name='position',
            field=models.CharField(default='', max_length=10),
        ),
    ]
