# Generated by Django 3.2.9 on 2022-03-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_gladns_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='size',
        ),
        migrations.RemoveField(
            model_name='terminal',
            name='type',
        ),
    ]
