# Generated by Django 3.2.9 on 2022-03-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_auto_20220309_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='size2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.sizeterminal'),
        ),
    ]
