# Generated by Django 3.2.9 on 2022-03-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_terminal_size2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='size2',
        ),
    ]
