# Generated by Django 3.2.9 on 2022-03-09 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_remove_terminal_size2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.sizeterminal'),
        ),
    ]
