# Generated by Django 3.2.9 on 2022-03-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0024_auto_20220309_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminals',
            name='position',
            field=models.CharField(default='', max_length=10),
        ),
    ]
