# Generated by Django 3.2.9 on 2022-03-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0026_alter_component_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='produkt_gladns_site_a',
        ),
        migrations.RemoveField(
            model_name='component',
            name='produkt_gladns_site_b',
        ),
        migrations.RemoveField(
            model_name='component',
            name='produkt_gladns_site_c',
        ),
        migrations.RemoveField(
            model_name='component',
            name='produkt_gladns_site_d',
        ),
        migrations.AddField(
            model_name='component',
            name='product_gladns_site_a',
            field=models.ManyToManyField(related_name='product_gladns_site_a_set', to='order.Gladns'),
        ),
        migrations.AddField(
            model_name='component',
            name='product_gladns_site_b',
            field=models.ManyToManyField(related_name='product_gladns_site_b_set', to='order.Gladns'),
        ),
        migrations.AddField(
            model_name='component',
            name='product_gladns_site_c',
            field=models.ManyToManyField(related_name='product_gladns_site_c_set', to='order.Gladns'),
        ),
        migrations.AddField(
            model_name='component',
            name='product_gladns_site_d',
            field=models.ManyToManyField(related_name='product_gladns_site_d_set', to='order.Gladns'),
        ),
    ]
